# =======================================================
# CONFIGURACIÓN COMÚN (SIN datasource aquí)
# =======================================================
spring:
  application:
    name: GestorLDS

  profiles:
    active: supabase

  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true

  jpa:
    show-sql: true

server:
  port: 8080

app:
  jwt:
    secret: "dev-secret-key-for-local-testing-256-bits-minimum"
    expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

---

# =======================================================
# PERFIL: SUPABASE (PostgreSQL en la nube)
# =======================================================
spring:
  config:
    activate:
      on-profile: supabase

  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
    username: postgres.omkreudnobfsarkxilmk
    password: doRddIThrfDM6YKP
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false